# Generated by Django 3.1.7 on 2021-04-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "name",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("title", models.TextField()),
                ("description", models.TextField()),
                ("url", models.TextField()),
                ("latitude", models.DecimalField(decimal_places=4, max_digits=8)),
                ("longitude", models.DecimalField(decimal_places=4, max_digits=8)),
                ("area", models.FloatField()),
                ("established", models.DateTimeField()),
                ("world_heritage_site", models.BooleanField()),
                ("visitors", models.IntegerField()),
                ("states", models.ManyToManyField(to="parks.State")),
            ],
        ),
    ]
